<a href="https://colab.research.google.com/github/Jojomaque/Portfolio/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
# Load libraries
import time  # timer
import numpy as np  # linear algebra
import pandas as pd  
import seaborn as sns  # plot handling
import matplotlib.pyplot as plt  # plot handling
import folium
import holoviews as hv

In [67]:
# Load Data
january = pd.read_csv('https://data.urbansharing.com/edinburghcyclehire.com/trips/v1/2021/01.csv')
february = pd.read_csv('https://data.urbansharing.com/edinburghcyclehire.com/trips/v1/2021/02.csv')
march = pd.read_csv('https://data.urbansharing.com/edinburghcyclehire.com/trips/v1/2021/03.csv')
april = pd.read_csv('https://data.urbansharing.com/edinburghcyclehire.com/trips/v1/2021/04.csv')
may = pd.read_csv('https://data.urbansharing.com/edinburghcyclehire.com/trips/v1/2021/05.csv')

In [68]:
Ed_Bike_2021.head()Ed_Bike_2021 = pd.concat([january, february, march, april, may])

SyntaxError: ignored

In [69]:
Ed_Bike_2021.end_station_name.nunique()

98

In [70]:
journeys = Ed_Bike_2021[['start_station_name','end_station_name']].value_counts()
journey_count = journeys.to_frame().reset_index()
journey_count.rename(columns = {'0':'journeys'}, inplace = True)
journey_count

           start_station_name         end_station_name    0
0     Portobello - Kings Road  Portobello - Kings Road  617
1               Pollock Halls  Portobello - Kings Road  604
2           Cramond Foreshore        Cramond Foreshore  539
3               Victoria Quay            Victoria Quay  459
4               Pollock Halls            Pollock Halls  347
...                       ...                      ...  ...
5410        Haymarket Terrace            Bristo Square    1
5411        Haymarket Terrace        Bruntsfield Links    1
5412        Haymarket Terrace              Duke Street    1
5413        Haymarket Terrace            Dundas Street    1
5414            Hunter Square      Pleasance Courtyard    1

[5415 rows x 3 columns]

In [63]:
top_journey = journey_count[:20]
top_journey

         start_station_name         end_station_name    0
0   Portobello - Kings Road  Portobello - Kings Road  617
1             Pollock Halls  Portobello - Kings Road  604
2         Cramond Foreshore        Cramond Foreshore  539
3             Victoria Quay            Victoria Quay  459
4             Pollock Halls            Pollock Halls  347
5   Portobello - Kings Road              Duke Street  343
6              Meadows East             Meadows East  328
7              Meadow Place             Meadow Place  309
8             Dynamic Earth            Dynamic Earth  309
9                Canonmills               Canonmills  308
10              Duke Street              Duke Street  302
11            Dynamic Earth  Portobello - Kings Road  272
12             Meadows East  Portobello - Kings Road  257
13             Meadow Place  Portobello - Kings Road  238
14        Bruntsfield Links             Meadows East  236
15             Meadow Place             Meadows East  212
16             Meadows East             Meadow Place  194
17              Duke Street  Portobello - Kings Road  174
18               Hawes Pier               Hawes Pier  173
19          Brunswick Place          Brunswick Place  167

In [50]:
least_journey = journey_count[-20:]
least_journey

            start_station_name                     end_station_name  0
5395               Grassmarket                        Surgeons Hall  1
5396                Hawes Pier                         Belford Road  1
5397                Hawes Pier                       Fountainbridge  1
5398                Hawes Pier                     Murrayfield Tram  1
5399                Hawes Pier                            Tollcross  1
5400         Haymarket Station                      Crichton Street  1
5401         Haymarket Terrace                        Dynamic Earth  1
5402         Haymarket Station                    Gamekeeper's Road  1
5403         Haymarket Station                    Gladstone Terrace  1
5404  Western General Hospital                     Charlotte Square  1
5405         Haymarket Station  Heriot Watt - Student Accommodation  1
5406         Haymarket Station                        Hunter Square  1
5407         Haymarket Station                  Pleasance Courtyard  1
5408         Haymarket Station                       Waverley Court  1
5409         Haymarket Terrace                          Boroughmuir  1
5410         Haymarket Terrace                        Bristo Square  1
5411         Haymarket Terrace                    Bruntsfield Links  1
5412         Haymarket Terrace                          Duke Street  1
5413         Haymarket Terrace                        Dundas Street  1
5414             Hunter Square                  Pleasance Courtyard  1